spring:
  datasource:
    url: jdbc:h2:mem:bd677ed7-b543-4e2e-8d83-570d91d0620f
    username: sa
    #password is empty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #show sql in the log
    show-sql: true
    properties:
      hibernate:
        #format the sql in the log
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  application:
    name: schoolservice
server:
  port: 8081
